version: '3.8'

services:
  semestre-service:
    image: juandiiego2111/semestreservice:latest
    container_name: semestre-service
    restart: unless-stopped
    depends_on:
      - db3
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      - DB_USER=postgres
      - DB_PASS=juandiego21
      - JPA_DDL=update
      - DB_HOST=jdbc:postgresql://localhost:5432/semestresdb
    networks:
      - mynetwork

  db3:
    image: postgres:latest
    container_name: db3
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: semestresdb
      POSTGRES_USER: postgres

networks:
  mynetwork:
    driver: bridge