services:
  semestre-service:
    image: juandiiego2111/semestreservice:latest
    container_name: semestreservice
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8082:8082"  # API principal
      - "8083:8083"  # Actuator
    environment:
      DB_USER: postgres
      DB_PASS: juandiego21
      JPA_DDL: create-drop
      DB_HOST: jdbc:postgresql://db:5432/semestresdb
      EUREKA_HOST: eurekaserver
      EUREKA_PORT: 8761
      PORT: 8082
      ACTUATOR_PORT: 8083
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=semestresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=juandiego21
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
