management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: ${ACTUATOR_PORT:8083}

spring:
  main:
    allow-circular-references: true

  datasource:
    hikari:
      validation-timeout: '5000'
      idle-timeout: '600000'
      maximum-pool-size: '50'
      connection-timeout: '30000'
      keepalive-time: '300000'
      max-lifetime: '1800000'
      connection-test-query: SELECT 1
      minimum-idle: '10'
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/semestresdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:juandiego21}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:create-drop}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  application:
    name: semestre-service

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        nodeValue: ERROR
        springframework: ERROR
    root: ERROR
    web: INFO
    com:
      zaxxer:
        hikari: ERROR

app:
  api:
    version: v1
  version: 0.14.0

server:
  port: ${PORT:8082}

programa-service:
  url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

  instance:
    prefer-ip-address: true
